LED_SETTINGS:
  DMA: 10
  GPIO_PIN: 10
  WIDTH: 144
  HEIGHT: 1
  BRIGHTNESS: 32
  GAMMA_CORRECTION: 2.0

AUDIO_SETTINGS:
  ALSA_INPUT_DEVICE: plughw:0
  FREQUENCY_BANDS: 4
  BAND_CUTOFF_FREQUENCIES: [ 20, 250, 1000, 4000, 20000 ]
  SAMPLE_RATE: 44100
  SAMPLES_PER_PIXEL: 1024
  PIXELS_PER_IMAGE: 144

SHADER_FOLDER: ../shaders